version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: backend_mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=backend
      - MYSQL_USER=backend_user
      - MYSQL_PASSWORD=123456
    ports:
      - "3303:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    networks:
      - backend_network
    command: --default-authentication-plugin=mysql_native_password

  # Tùy chọn: phpMyAdmin để quản lý database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: backend_phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=123456
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - backend_network

volumes:
  mysql_data:

networks:
  backend_network:
    driver: bridge
